import warnings
import copy
import numpy as np

from lys.errors import NotImplementedWarning

from .CanvasBase import saveCanvas
from .WaveData import WaveData


class ScatterData(WaveData):
    """
    Interface to access scatter plot data in the canvas.

    Instance of ScatterData is automatically generated by display or append methods.

    Example::

        from lys import display
        g = display([1,2,3])
        g.getScatters()[0].setColor('#ff0000')
    """

    def __setAppearance(self, key, value):
        self._appearance[key] = value

    def __getAppearance(self, key, default=None):
        return self._appearance.get(key, default)

    @saveCanvas
    def setColormap(self, cmap):
        """
        Set colormap of the scatter plot.

        Args:
            colormap(str): colormap string such as 'gray'.
        """
        self.__setAppearance('Colormap', cmap)
        self._setColormap(cmap)

    def getColormap(self):
        """
        Get colormap of the scatter plot.

        Return:
            str: colormap string such as 'gray'
        """
        return self.__getAppearance('Colormap', 'gray')

    @saveCanvas
    def setGamma(self, gamma):
        """
        Set gamma value of the scatter plot.

        Args:
            gamma(float): The gamma value.
        """
        self.__setAppearance('ColorGamma', gamma)
        self._setGamma(gamma)

    def getGamma(self):
        """
        Get the gamma value of the scatter plot.

        Return:
            float: The gamma value.
        """
        return self.__getAppearance('ColorGamma', 1.0)

    @saveCanvas
    def setOpacity(self, opacity):
        """
        Set the opacity of the scatter plot.

        Args:
            opacity(float): The opacity.
        """
        self.__setAppearance('ColormapOpacity', opacity)
        self._setColormapOpacity(opacity)

    def getOpacity(self):
        """
        Get the opacity of the scatter plot.

        Return:
            float: The opacity.
        """
        return self.__getAppearance('ColormapOpacity', 1.0)

    @saveCanvas
    def setColorRange(self, min='auto', max='auto'):
        """
        Set the color range of the scatter plot.

        Args:
            min(float or 'auto'): The minimum value of the range.
            max(float or 'auto'): The maximum value of the range.
        """
        automin, automax = self.getAutoColorRange()
        if max == 'auto':
            max = automax
        if min == 'auto':
            min = automin
        if max < min:
            max = min
        if self.isLog() and (min <= 0 or max <= 0):
            warnings.warn('[Image.setColorRange] Values must all be positive to use log plot. Log is disabled.', RuntimeWarning)
            self.setLog(True)
        self.__setAppearance('Range', (min, max))
        self._setColorRange(min, max)

    def getColorRange(self):
        """
        Get the color range of the scatter plot.

        Return:
            tuple of length 2: minimum and maximum value of the range.
        """
        return self.__getAppearance('Range')

    def getAutoColorRange(self):
        """
        Get the automarically-calculated color range of the scatter plot, which is used by :meth:`setColorRange` method.

        Return:
            tuple of length 2: minimum and maximum value of the range.
        """
        dat = np.nan_to_num(self.getFilteredWave().data)
        ma, mi = np.percentile(dat, [95, 5])
        dat = np.clip(dat, mi, ma)
        var = np.sqrt(dat.var()) * 3
        if var == 0:
            var = 1
        mean = dat.mean()
        if np.min(dat) >= 0 and mean - var < 0:
            return (0, mean + var)
        else:
            return (mean - var, mean + var)

    @saveCanvas
    def setLog(self, log):
        """
        Set the color scale to be logarithmic.

        Args:
            log(bool): If *log* is True, logarithmic scale is enabled.
        """
        self.__setAppearance('Log', log)
        self._setLog(log)

    def isLog(self):
        """
        Return true if the color scale is logarithmic.

        Return:
            bool: If True, logarithmic scale is enabled.
        """
        return self.__getAppearance('Log')

    @saveCanvas
    def setColorbarVisible(self, visible):
        """
        Set the visibility of the colorbar.

        Args:
            visible(bool): The visibility.
        """
        self._setColorbarVisible(visible)
        self.__setAppearance("colorbarVisible", visible)
        self.canvas().refreshCanvasSize()
        self.canvas().refreshMargin()

    def getColorbarVisible(self):
        """
        Get the visibility of the colorbar.

        Returns:
            bool: The visibility.
        """
        return self.__getAppearance('colorbarVisible', False)

    @saveCanvas
    def setColorbarDirection(self, direction):
        """
        Set the direction of the colorbar.

        Args:
            direction ('vretical' or 'horizontal'): The direction of the colorbar.
        """
        self._setColorbarDirection(direction)
        self.__setAppearance("colorbarDirection", direction)
        self.canvas().refreshCanvasSize()
        self.canvas().refreshMargin()

    def getColorbarDirection(self):
        """
        Get the direction of the colorbar.

        Returns:
            str: The direction of the colorbar.
        """
        return self.__getAppearance("colorbarDirection", "vertical")

    @saveCanvas
    def setColorbarPosition(self, pos):
        """
        Set the position of the colorbar.

        Args:
            pos(length 2 float): The position of the colorbar in the form of (x,y).
        """
        self._setColorbarPosition(pos)
        self.__setAppearance("colorbarPosition", pos)

    def getColorbarPosition(self):
        """
        Get the position of the colorbar.

        Returns:
            length 2 float: The position of the colorbar.
        """
        return self.__getAppearance('colorbarPosition', (0.02, 0))

    @saveCanvas
    def setColorbarSize(self, size):
        """
        Set the size of the colorbar.

        Args:
            size(length 2 float): The size of the colorbar in the form of (width, height).
        """
        self._setColorbarSize(size)
        self.__setAppearance("colorbarSize", size)

    def getColorbarSize(self):
        """
        Get the size of the colorbar.

        Returns:
            length 2 float: The size of the colorbar.
        """
        return self.__getAppearance('colorbarSize', (0.04, 1))

    @saveCanvas
    def setLineColorByData(self, bool):
        """
        Set whether to use the line colormap for the scatter plot.
        
        Args:
            bool (bool): Whether to use the line colormap for the scatter plot.
        """
        self.__setAppearance('LineColorByData', bool)
        if bool:
            self._setColormap(self.getColormap())
        else:
            self._setLineColor(self.getLineColor())

    def getLineColorByData(self):
        """
        Get whether to use the line colormap for the scatter plot.
        
        Returns:
            bool: Whether to use the line colormap for the scatter plot.
        """
        return self.__getAppearance('LineColorByData', False)
    
    @saveCanvas
    def setLineWidthByData(self, bool):
        """
        Set whether to use the line width by data for the scatter plot.
        
        Args:
            bool (bool): Whether to use the line width by data for the scatter plot.
        """
        # self._setLineWidthByData(bool)
        self.__setAppearance('LineWidthByData', bool)
        if bool:
            self._setLineWidthExpression(self.getLineWidthExpression())
        else:
            self._setLineWidth(self.getLineWidth())

    def getLineWidthByData(self):
        """
        Get whether to use the line width by data for the scatter plot.
        
        Returns:
            bool: Whether to use the line width by data for the scatter plot.
        """
        return self.__getAppearance('LineWidthByData', False)
    
    @saveCanvas
    def setLineWidthExpression(self, expression):
        """
        Set the expression for the line width.
        
        Args:
            expression(str): The expression for the line width.
        """
        self._setLineWidthExpression(expression)
        self.__setAppearance('LineWidthExpression', expression)

    def getLineWidthExpression(self):
        """
        Get the expression for the line width.
        
        Returns:
            str: The expression for the line width.
        """
        return self.__getAppearance('LineWidthExpression', 'z')

    @saveCanvas
    def setLineWidthRange(self, max):
        """
        Set the range for the line width.
        
        Args:
            max (float): The maximum value for the line width.
        """
        self.__setAppearance('LineWidthRange', max)
        self._setLineWidthRange(max)
    
    def getLineWidthRange(self):
        """
        Get the range for the line width.
        
        Returns:
            float: The maximum value for the line width.
        """
        return self.__getAppearance('LineWidthRange', 5)

    @saveCanvas
    def setLineColor(self, color):
        """
        Set the color of the line.
        
        Args:
            color(str): The color of the line.
        """
        self._setLineColor(color)
        self.__setAppearance('LineColor', color)

    def getLineColor(self):
        """
        Get the color of the line.
        
        Returns:
            str: The color of the line.
        """
        return self.__getAppearance('LineColor', 'black')

    @saveCanvas
    def setLineOpacity(self, opacity):
        """
        Set the opacity of the line.
        
        Args:
            opacity(float): The opacity of the line.
        """
        self._setLineOpacity(opacity)
        self.__setAppearance('LineOpacity', opacity)

    def getLineOpacity(self):
        """
        Get the opacity of the line.
        
        Returns:
            float: The opacity of the line.
        """
        return self.__getAppearance('LineOpacity', 1.0)

    @saveCanvas
    def setLineStyle(self, style):
        """
        Set the style of the line.

        Args:
            style('solid', 'dashed', 'dashdot', 'dotted', 'None'): Style string. 
        """
        self.__setAppearance('LineStyle', style)
        self._setLineStyle(style)

    def getLineStyle(self):
        """
        Get the style of the line.

        Return:
            str: Style string.
        """
        return self.__getAppearance('LineStyle')

    @saveCanvas
    def setLineWidth(self, width):
        """
        Set the width of the line.

        Args:
            width(float): The width of the line.
        """
        self.__setAppearance('LineWidth', width)
        self._setLineWidth(width)

    def getLineWidth(self):
        """
        Get the width of the line.

        Return:
            float: The width of the line.
        """
        return self.__getAppearance('LineWidth')

    @saveCanvas
    def setMarker(self, marker):
        """
        Set the marker shape.

        Args:
            marker(str): String that indicate the marker shape. List of style strings can be seen from matplotlib.lines.Line2D.markers.values(). 
        """
        self.__setAppearance('Marker', marker)
        self._setMarker(marker)

    def getMarker(self):
        """
        Get the marker shape.

        Return:
            str: String that indicate the marker shape. List of style strings can be seen from matplotlib.lines.Line2D.markers.values(). 
        """
        return self.__getAppearance('Marker')

    @saveCanvas
    def setMarkerColorByData(self, bool):
        """
        Set whether to use the marker colormap for the scatter plot.
        
        Args:
            bool (bool): Whether to use the marker colormap for the scatter plot.
        """
        self.__setAppearance('MarkerColorByData', bool)
        if bool:
            self._setColormap(self.getColormap())
        else:
            self._setMarkerColor(self.getMarkerColor())

    def getMarkerColorByData(self):
        """
        Get whether to use the marker colormap for the scatter plot.
        
        Returns:
            bool: Whether to use the marker colormap for the scatter plot.
        """
        return self.__getAppearance('MarkerColorByData', True)
    
    @saveCanvas
    def setMarkerColor(self, color):
        """
        Set the color of the marker.
        
        Args:
            color(str): The color of the marker.
        """
        self.__setAppearance('MarkerColor', color)
        self._setMarkerColor(color)

    def getMarkerColor(self):
        """
        Get the color of the marker.
        
        Returns:
            str: The color of the marker.
        """
        return self.__getAppearance('MarkerColor', 'black')
    
    @saveCanvas
    def setMarkerOpacity(self, opacity):
        """
        Set the opacity of the marker.
        
        Args:
            opacity(float): The opacity of the marker.
        """
        self._setMarkerOpacity(opacity)
        self.__setAppearance('MarkerOpacity', opacity)

    def getMarkerOpacity(self):
        """
        Get the opacity of the marker.
        
        Returns:
            float: The opacity of the marker.
        """
        return self.__getAppearance('MarkerOpacity', 1.0)

    @saveCanvas
    def setMarkerSizeByData(self, bool):
        """
        Set whether to use the marker size by data for the scatter plot.
        
        Args:
            bool (bool): Whether to use the marker size by data for the scatter plot.
        """
        self.__setAppearance('MarkerSizeByData', bool)
        if bool:
            self._setMarkerSizeExpression(self.getMarkerSizeExpression())
        else:
            self._setMarkerSize(self.getMarkerSize())

    def getMarkerSizeByData(self):
        """
        Get whether to use the marker size by data for the scatter plot.
        
        Returns:
            bool: Whether to use the marker size by data for the scatter plot.
        """
        return self.__getAppearance('MarkerSizeByData', False)
    
    @saveCanvas
    def setMarkerSizeExpression(self, expression):
        """
        Set the expression for the marker size.
        
        Args:
            expression(str): The expression for the marker size.
        """
        self._setMarkerSizeExpression(expression)
        self.__setAppearance('MarkerSizeExpression', expression)

    def getMarkerSizeExpression(self):
        """
        Get the expression for the marker size.
        
        Returns:
            str: The expression for the marker size.
        """
        return self.__getAppearance('MarkerSizeExpression', 'z')

    @saveCanvas
    def setMarkerSizeRange(self, max):
        """
        Set the range for the marker size.
        
        Args:
            max (float): The maximum value for the marker size.
        """
        self._setMarkerSizeRange(max)
        self.__setAppearance('MarkerSizeRange', max)

    
    def getMarkerSizeRange(self):
        """
        Get the range for the marker size.
        
        Returns:
            float: The range for the marker size.
        """
        return self.__getAppearance('MarkerSizeRange', 10)

    @saveCanvas
    def setMarkerSize(self, size):
        """
        Set the size of the marker.

        Args:
            size(float): The size of the marker.
        """
        self._setMarkerSize(size)
        self.__setAppearance('MarkerSize', size)

    def getMarkerSize(self):
        """
        Get the size of the marker.

        Return:
            float: The size of the marker.
        """
        return self.__getAppearance('MarkerSize')

    @saveCanvas
    def setMarkerThick(self, thick):
        """
        Set the thickness of the marker edge.

        Args:
            thick(float): The thickness of the marker edge.
        """
        self.__setAppearance('MarkerThick', thick)
        self._setMarkerThick(thick)

    def getMarkerThick(self):
        """
        Get the thickness of the marker edge.

        Return:
            float: The thickness of the marker edge.
        """
        return self.__getAppearance('MarkerThick')

    @saveCanvas
    def setMarkerFilling(self, type):
        """
        Set the filling of the marker.

        Args:
            type('full', 'left', 'ritght', 'top', 'bottom', or 'none'): Style string. 
        """

        self.__setAppearance('MarkerFilling', type)
        self._setMarkerFilling(type)

    def getMarkerFilling(self):
        """
        Get the filling of the marker.

        Return:
            str: Style string.
        """
        return self.__getAppearance('MarkerFilling')

    @saveCanvas
    def setErrorbar(self, error, direction="y"):
        """
        Set the errorbar.

        If the error is float, the constant errorbar is set.

        If the error is str, the errorbar is loaded from wave.note[error].

        If the error is an array, the array is used as the errorbar.

        Args:
            error(float or str or array): The error.
            direction('x' or 'y'): The direction of the errorbar
        """
        err = self._getErrorbarData(error)
        self._setErrorbar(err, direction)
        if direction == 'x':
            self.__setAppearance("xerror", error)
        elif direction == 'y':
            self.__setAppearance("yerror", error)

    def __checkErrorShape(self, val):
        if isinstance(val, float):
            return True
        elif np.array(val).shape == (len(self.getFilteredWave().data),):
            return True
        elif np.array(val).shape == (2, len(self.getFilteredWave().data)):
            return True
        return False

    def getErrorbar(self, direction="y"):
        """
        Get the errorbar.

        Args:
            direction('x' or 'y'): The direction of the errorbar

        Returns:
            list: The errorbar
        """
        if direction == "x":
            return self.__getAppearance('xerror')
        elif direction == 'y':
            return self.__getAppearance('yerror')

    def _getErrorbarData(self, error):
        err = copy.deepcopy(error)
        if isinstance(err, str):
            err = self.getWave().note.get(err)
        if hasattr(err, "__iter__"):
            err = np.abs(np.array(err))
        if err is not None:
            if not self.__checkErrorShape(err):
                err = None
        return err

    @saveCanvas
    def setCapSize(self, capsize):
        """
        Set the cap size of the errorbar.

        Args:
            capsize(float): The cap size.
        """
        self._setCapSize(capsize)
        self.__setAppearance("capsize", capsize)

    def getCapSize(self):
        """
        Get the cap size of the errorbar.

        Returns:
            float: The cap size.
        """
        return self.__getAppearance('capsize', 0)

    @saveCanvas
    def setLegendVisible(self, visible):
        """
        Set the visibility of the legend.

        Args:
            visible(bool): The visibility.
        """
        self.__setAppearance("legendVisible", visible)
        self._setLegendVisible(visible)

    def getLegendVisible(self):
        """
        Get the visibility of the legend.

        Returns:
            bool: The visibility.
        """
        return self.__getAppearance('legendVisible', False)

    @saveCanvas
    def setLegendLabel(self, label):
        """
        Set the label of the legend.

        Args:
            label(str): The label.
        """
        self.__setAppearance("legendLabel", label)
        self._setLegendLabel(label)

    def getLegendLabel(self):
        """
        Get the label of the legend.

        Returns:
            str: The label.
        """
        return self.__getAppearance('legendLabel', '')


    def _loadAppearance(self, appearance):
        self.setMarker(appearance.get('Marker', 'circle'))
        self.setMarkerSize(appearance.get('MarkerSize', 6))
        self.setMarkerFilling(appearance.get('MarkerFilling', 'full'))
        self.setMarkerThick(appearance.get('MarkerThick', 1))
        self.setMarkerOpacity(appearance.get('MarkerOpacity', 1.0))
        self.setMarkerColor(appearance.get('MarkerColor', 'blue'))
        self.setMarkerColorByData(appearance.get('MarkerColorByData', True))
        self.setMarkerSizeRange(appearance.get('MarkerSizeRange', 10))
        self.setMarkerSizeExpression(appearance.get('MarkerSizeExpression', 'z'))
        self.setMarkerSizeByData(appearance.get('MarkerSizeByData', False))
        self.setLineStyle(appearance.get('LineStyle', 'None'))
        self.setLineWidth(appearance.get('LineWidth', 2))
        self.setLineOpacity(appearance.get('LineOpacity', 1.0))
        self.setLineColor(appearance.get('LineColor', 'blue'))
        self.setLineColorByData(appearance.get('LineColorByData', False))
        self.setLineWidthExpression(appearance.get('LineWidthExpression', 'z'))
        self.setLineWidthByData(appearance.get('LineWidthByData', False))
        self.setErrorbar(appearance.get('xerror'), "x")
        self.setErrorbar(appearance.get('yerror'), "y")
        self.setCapSize(appearance.get('capsize', 0))
        self.setLegendLabel(appearance.get('legendLabel', self.getName()))
        self.setLegendVisible(appearance.get('legendVisible', False))
        self.setColormap(appearance.get('Colormap', 'gray'))
        self.setGamma(appearance.get('ColorGamma', 1.0))
        self.setOpacity(appearance.get('ColormapOpacity', 1.0))
        self.setColorRange(*appearance.get('Range', self.getAutoColorRange()))
        self.setLog(appearance.get('Log', False))
        self.setColorbarVisible(appearance.get('colorbarVisible', False))
        self.setColorbarDirection(appearance.get('colorbarDirection', "vertical"))
        self.setColorbarPosition(appearance.get('colorbarPosition', (0.02, 0)))
        self.setColorbarSize(appearance.get('colorbarSize', (0.04, 1)))

    def _setColormap(self, colormap):
        warnings.warn(str(type(self)) + " does not implement _setColormap(colormap) method.", NotImplementedWarning)

    def _setGamma(self, gamma):
        warnings.warn(str(type(self)) + " does not implement _setGamma(gamma) method.", NotImplementedWarning)

    def _setColormapOpacity(self, opacity):
        warnings.warn(str(type(self)) + " does not implement _setColormapOpacity(opacity) method.", NotImplementedWarning)

    def _setColorRange(self, min, max):
        warnings.warn(str(type(self)) + " does not implement _setColorRange(min, max) method.", NotImplementedWarning)

    def _setLog(self, log):
        warnings.warn(str(type(self)) + " does not implement _setLog(log) method.", NotImplementedWarning)

    def _setColorbarVisible(self, visible):
        warnings.warn(str(type(self)) + " does not implement _setColorbarVisible(visible) method.", NotImplementedWarning)

    def _setColorbarDirection(self, direction):
        warnings.warn(str(type(self)) + " does not implement _setColorbarDirection(direction) method.", NotImplementedWarning)

    def _setColorbarPosition(self, pos):
        warnings.warn(str(type(self)) + " does not implement _setColorbarPosition(pos) method.", NotImplementedWarning)

    def _setColorbarSize(self, size):
        warnings.warn(str(type(self)) + " does not implement _setColorbarSize(size) method.", NotImplementedWarning)

    def _setMarker(self, marker):
        warnings.warn(str(type(self)) + " does not implement _setMarker(marker) method.", NotImplementedWarning)

    def _setMarkerColor(self, color):
        warnings.warn(str(type(self)) + " does not implement _setMarkerColor(color) method.", NotImplementedWarning)
           
    def _setMarkerSizeExpression(self, expression):
        warnings.warn(str(type(self)) + " does not implement _setMarkerSizeExpression(expression) method.", NotImplementedWarning)
    
    def _setMarkerSizeRange(self, max):
        warnings.warn(str(type(self)) + " does not implement _setMarkerSizeRange(max) method.", NotImplementedWarning)

    def _setMarkerSize(self, size):
        warnings.warn(str(type(self)) + " does not implement _setMarkerSize(size) method.", NotImplementedWarning)

    def _setMarkerThick(self, thick):
        warnings.warn(str(type(self)) + " does not implement _setMarkerThick(thick) method.", NotImplementedWarning)

    def _setMarkerFilling(self, type):
        warnings.warn(str(type(self)) + " does not implement _setMarkerFilling(filling) method.", NotImplementedWarning)
    
    def _setMarkerOpacity(self, opacity):
        warnings.warn(str(type(self)) + " does not implement _setMarkerOpacity(opacity) method.", NotImplementedWarning)    

    def _setLineStyle(self, style):
        warnings.warn(str(type(self)) + " does not implement _setStyle(style) method.", NotImplementedWarning)

    def _setLineWidth(self, width):
        warnings.warn(str(type(self)) + " does not implement _setWidth(width) method.", NotImplementedWarning)

    def _setLineColor(self, color):
        warnings.warn(str(type(self)) + " does not implement _setLineColor(color) method.", NotImplementedWarning)

    def _setLineWidthRange(self, max):
        warnings.warn(str(type(self)) + " does not implement _setLineWidthRange(max) method.", NotImplementedWarning)

    def _setLineWidthExpression(self, expression):
        warnings.warn(str(type(self)) + " does not implement _setLineWidthExpression(expression) method.", NotImplementedWarning)
    
    def _setLineOpacity(self, opacity):
        warnings.warn(str(type(self)) + " does not implement _setLineOpacity(opacity) method.", NotImplementedWarning)
    
    def _setErrorbar(self, error, direction):
        warnings.warn(str(type(self)) + " does not implement _setErrorbar(error, direction) method.", NotImplementedWarning)
    
    def _setCapSize(self, capsize):
        warnings.warn(str(type(self)) + " does not implement _setCapSize(capsize) method.", NotImplementedWarning)

    def _setLegendVisible(self, visible):
        warnings.warn(str(type(self)) + " does not implement _setLegendVisible(visible) method.", NotImplementedWarning)

    def _setLegendLabel(self, label):
        warnings.warn(str(type(self)) + " does not implement _setLegendLabel(label) method.", NotImplementedWarning)

